#!/usr/bin/env php
<?php

defined('APPLICATION_PATH') || define(
    'APPLICATION_PATH',
    realpath(dirname(__FILE__) . '/src')
);

set_include_path(
    implode(
        PATH_SEPARATOR,
        array(
            realpath(APPLICATION_PATH . '/../library/IRCBot/src'),
            APPLICATION_PATH,
            get_include_path(),
        )
    )
);

require_once 'src/Application.php';

$application = new BotLife_Application();
$application->bootstrap()
    ->run();
